const locationsData = {
    brickell: {
        name: 'Brickell',
        title: 'Brickell, Miami, FL',
        address: '420 SW 7th Street',
        fullAddress: '420 SW 7th Street, Miami, FL 33130',
        city: 'Miami',
        state: 'FL',
        images: [
            '/images/storage/brickell-1.png',
            '/images/storage/brickell-2.png',
            '/images/storage/brickell-3.png',
        ],
        alt: 'Brickell, Miami, FL',
        phone: '+1 (786) 635-1301',
        email: 'contact@megacenter.com',
        mapQuery: 'Megacenter%Brickell',
        mapTitle: 'Megacenter Brickell, Miami',
        url: 'storage/brickell/',
        accessHours: 'Mon - Sun: 6:00 - 22:00',
        officeHours: 'Mon - Sat: 9:00 - 17:00',
        detailedHours: {
            access: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: '6:00 - 21:00' },
            ],
            office: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: 'Closed' },
            ],
        },
    },
    willowbrook: {
        name: 'Willowbrook',
        title: 'Willowbrook, Houston, TX',
        address: '7075 FM 1960',
        fullAddress: '7075 FM 1960, Houston, TX 77069',
        city: 'Houston',
        state: 'TX',
        images: [
            '/images/storage/willowbrook-1.png',
            '/images/storage/willowbrook-2.png',
        ],
        alt: 'Willowbrook, Houston, TX',
        phone: '+1 (832) 930-9100',
        email: 'contact@megacenter.com',
        mapQuery: 'Megacenter%Willowbrook',
        mapTitle: 'Megacenter Willowbrook, Houston',
        url: 'storage/willowbrook/',
        accessHours: 'Mon - Sun: 6:00 - 21:00',
        officeHours: 'Mon - Sat: 9:00 - 17:00',
        detailedHours: {
            access: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: '6:00 - 21:00' },
            ],
            office: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: 'Closed' },
            ],
        },
    },
    memorial: {
        name: 'Memorial',
        title: 'Memorial, Houston, TX',
        address: '1530 W Sam Pkwy N',
        fullAddress: '1530 W Sam Pkwy N, Houston, TX 77043',
        city: 'Houston',
        state: 'TX',
        images: [
            '/images/storage/memorial-1.png',
            '/images/storage/memorial-2.png',
        ],
        alt: 'Memorial, Houston, TX',
        phone: '+1 (713) 254-7893',
        email: 'contact@megacenter.com',
        mapQuery: 'Megacenter Memorial, Houston',
        mapTitle: 'Megacenter Memorial, Houston',
        url: 'storage/memorial/',
        accessHours: 'Mon - Sun: 6:00 - 21:00',
        officeHours: 'Mon - Sat: 9:00 - 17:00',
        detailedHours: {
            access: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: '6:00 - 21:00' },
            ],
            office: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: 'Closed' },
            ],
        },
    },
    demo: {
        name: 'Demo',
        title: 'Demo Location - Test Site',
        address: '420 SW 7th Street',
        fullAddress: '420 SW 7th Street, Demo City, DM 00000',
        city: 'Demo City',
        state: 'DM',
        images: [
            '/images/storage/brickell-1.png',
            '/images/storage/brickell-2.png',
            '/images/storage/brickell-3.png',
        ],
        alt: 'Demo Location',
        phone: '+1 (555) 000-0000',
        email: 'demo@megacenter.com',
        mapQuery: 'Megacenter%Brickell',
        mapTitle: 'Megacenter Brickell, Miami',
        url: 'storage/demo/',
        accessHours: 'Mon - Sat: 6:00 - 21:00',
        officeHours: 'Mon - Sun: 9:00 - 17:00',
        detailedHours: {
            access: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: '6:00 - 21:00' },
            ],
            office: [
                { day: 'Monday', hours: '6:00 - 21:00' },
                { day: 'Tuesday', hours: '6:00 - 21:00' },
                { day: 'Wednesday', hours: '6:00 - 21:00' },
                { day: 'Thursday', hours: '6:00 - 21:00' },
                { day: 'Friday', hours: '6:00 - 21:00' },
                { day: 'Saturday', hours: '6:00 - 21:00' },
                { day: 'Sunday', hours: '6:00 - 21:00' },
            ],
        },
    },
};

module.exports = locationsData;
