/**
 * Tenant Service
 *
 * Service for managing tenants in SiteLink
 * Used by both reservations and move-in flows
 */

const client = require('../shared/client');
const { logInfo } = require('../../middleware/logger');

/**
 * Helper: Remove null/undefined fields and empty strings for date fields
 * SiteLink SOAP doesn't accept empty strings for certain types
 */
function cleanSoapArgs(args) {
	const cleaned = {};
	for (const [key, value] of Object.entries(args)) {
		// Skip null/undefined
		if (value === null || value === undefined) {
			continue;
		}
		// Skip empty strings for date fields (dDOB, etc)
		if (key.startsWith('d') && value === '') {
			continue;
		}
		cleaned[key] = value;
	}
	return cleaned;
}

/**
 * Create a new tenant
 * Calls TenantNewDetailed_v2
 *
 * @param {object} tenantData - Tenant information
 * @param {string} tenantData.firstName - First name (required)
 * @param {string} tenantData.lastName - Last name (required)
 * @param {string} tenantData.email - Email address
 * @param {string} tenantData.phone - Phone number
 * @param {string} tenantData.address - Address
 * @param {string} tenantData.city - City
 * @param {string} tenantData.state - State
 * @param {string} tenantData.zipCode - Zip code
 * @param {string} tenantData.notes - Notes/comments
 * @param {string} locationCode - Location code override (optional)
 * @returns {Promise<object>} Parsed response with TenantID and AccessCode
 */
async function createTenant(tenantData, locationCode = null) {
	const args = cleanSoapArgs({
		sWebPassword: '',
		sMrMrs: '',
		sFName: tenantData.firstName,
		sMI: '',
		sLName: tenantData.lastName,
		sCompany: '',
		sAddr1: tenantData.address || '',
		sAddr2: '',
		sCity: tenantData.city || '',
		sRegion: tenantData.state || '',
		sPostalCode: tenantData.zipCode || '',
		sCountry: '',
		sPhone: tenantData.phone || '',
		// Alt contact (empty)
		sMrMrsAlt: '',
		sFNameAlt: '',
		sMIAlt: '',
		sLNameAlt: '',
		sCompanyAlt: '',
		sAddr1Alt: '',
		sAddr2Alt: '',
		sCityAlt: '',
		sRegionAlt: '',
		sPostalCodeAlt: '',
		sCountryAlt: '',
		sPhoneAlt: '',
		// Bus contact (empty)
		sMrMrsBus: '',
		sFNameBus: '',
		sMIBus: '',
		sLNameBus: '',
		sCompanyBus: '',
		sAddr1Bus: '',
		sAddr2Bus: '',
		sCityBus: '',
		sRegionBus: '',
		sPostalCodeBus: '',
		sCountryBus: '',
		sPhoneBus: '',
		// Other fields
		sFax: '',
		sEmail: tenantData.email || '',
		sPager: '',
		sMobile: tenantData.phone || '',
		bCommercial: false,
		bCompanyIsTenant: false,
		dDOB: null, // This will be removed by cleanSoapArgs
		sTenNote: tenantData.notes || '',
		sLicense: '',
		sLicRegion: '',
		sSSN: '',
		sGateCode: '', // Auto-generated by SiteLink
	});

	logInfo('TenantService', 'Creating tenant', {
		firstName: tenantData.firstName,
		lastName: tenantData.lastName,
	});

	const response = await client.callMethod(
		'TenantNewDetailed_v2',
		args,
		'callCenter',
		locationCode
	);

	// Extract TenantID and AccessCode from RT table
	// According to SiteLink docs, RT contains: Ret_Code, TenantID, AccessCode
	const rtData = Array.isArray(response.data.RT)
		? response.data.RT[0]
		: response.data.RT;

	// Validate tenant was created successfully
	if (!rtData || !rtData.TenantID) {
		throw new Error(
			`Failed to create tenant: ${response.retMsg || 'Unknown error'}`
		);
	}

	logInfo('TenantService', 'Tenant created', {
		tenantId: rtData.TenantID,
		accessCode: rtData.AccessCode,
	});

	return {
		tenantId: parseInt(rtData.TenantID),
		accessCode: rtData.AccessCode,
		rawResponse: response,
	};
}

module.exports = {
	createTenant,
};
